### ISSUE TITLE
Cant compile, error 😢

### ISSUE THREAD

**Issue by PweJolo** [YoshiokaHaruki/AMXX-Floating-Damage#1]
addon_floating_damage.sma(257) : error 017: undefined symbol "xs_vec_add_scaled
addon_floating_damage.sma(432) : error 017: undefined symbol "xs_vec_add_scaled
addon_floating_damage.sma(562) : error 017: undefined symbol "xs_vec_distance

**Comment by YoshiokaHaruki** [comment]
@PweJolo Update your xs.inc. Or just add this code to the plugin

```sma
stock xs_vec_add_scaled(const Float:in1[], const Float:in2[], Float:scalar, Float:out[])
{
	out[0] = in1[0] + in2[0] * scalar;
	out[1] = in1[1] + in2[1] * scalar;
	out[2] = in1[2] + in2[2] * scalar;
}

stock Float:xs_vec_distance(const Float:vec1[], const Float:vec2[])
{
	return xs_sqrt((vec1[0]-vec2[0]) * (vec1[0]-vec2[0]) +
	               (vec1[1]-vec2[1]) * (vec1[1]-vec2[1]) +
	               (vec1[2]-vec2[2]) * (vec1[2]-vec2[2]));
}
```

**Comment by PweJolo** [comment]
> @PweJolo Update your xs.inc. Or just add this code to the plugin
> 
> ```pawn
> stock xs_vec_add_scaled(const Float:in1[], const Float:in2[], Float:scalar, Float:out[])
> {
> 	out[0] = in1[0] + in2[0] * scalar;
> 	out[1] = in1[1] + in2[1] * scalar;
> 	out[2] = in1[2] + in2[2] * scalar;
> }
> 
> stock Float:xs_vec_distance(const Float:vec1[], const Float:vec2[])
> {
> 	return xs_sqrt((vec1[0]-vec2[0]) * (vec1[0]-vec2[0]) +
> 	               (vec1[1]-vec2[1]) * (vec1[1]-vec2[1]) +
> 	               (vec1[2]-vec2[2]) * (vec1[2]-vec2[2]));
> }
> ```

Thanks, its fixed now 🙏
